name: Build and Push Docker Images to ACR

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend-tooltrack ./frontend2
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/frontend-tooltrack

    - name: Build and push backend image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend-tooltrack ./backend
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend-tooltrack
