FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Set port environment variable
ENV PORT 3000

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]